add support for binary streaming
medizininformatik-initiative/mii-process-data-transfer pull request #35
Opened 2024-12-18 14:26 UTC by wetret

resolves #34

2025-03-03 19:30 UTC, hhund requested changes
There are still Binary resource being serialized between BPMN tasks. Is this enough of an improvement to handle larger Binary resource?

2025-03-03 19:30 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/spring/config/DicFhirClientConfig.java
> +				proxyPassword, fhirStoreHapiClientVerbose, 5, fhirContext, localIdentifierValue, dataLogger());
Should the "initialPollingIntervalMilliseconds" be configurable? Maybe use `FhirClientFactory.DEFAULT_INITIAL_POLLING_INTERVAL_MILLISECONDS` to show that we don't care here.

2025-03-03 19:30 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/spring/config/DmsFhirClientConfig.java
> +				proxyPassword, fhirStoreHapiClientVerbose, 5, fhirContext, localIdentifierValue, dataLogger());
Should the "initialPollingIntervalMilliseconds" be configurable? Maybe use `FhirClientFactory.DEFAULT_INITIAL_POLLING_INTERVAL_MILLISECONDS` to show that we don't care here.

2025-03-03 19:30 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/service/ReadData.java
> +			return new Binary().setData(attachment.stream.readAllBytes()).setContentType(attachment.mimetype);
If we create a Binary resource here and later store the resource in a process variable, the resource will be serialized between this and the next BPMN task. This would move the size constraint problem into the BPMN and thus may not solve #34.
Storing byte array and mime type separately might be a workaround to at least get rid of the base64 encoding step. The correct solution would store the URL to binary here and later pass the "read" InputStream directly to the FHIR client storing the resource.

2025-03-03 19:30 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/service/InsertData.java
> +	private IdType createBinary(Binary binary)
Since the Binary resource is extracted from a Bundle resource that was stored in a BPMN variable. The Binary resource will have been serialized between BPMN tasks. Using a stream based create method here, removes one serialization step, but may not solve #34.

2025-03-04 08:28 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/spring/config/DicFhirClientConfig.java
> +				proxyPassword, fhirStoreHapiClientVerbose, 5, fhirContext, localIdentifierValue, dataLogger());
implemented in 7227d20

2025-03-04 08:28 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/spring/config/DmsFhirClientConfig.java
> +				proxyPassword, fhirStoreHapiClientVerbose, 5, fhirContext, localIdentifierValue, dataLogger());
implemented in 7227d20

2025-03-04 08:30 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/service/ReadData.java
> +			return new Binary().setData(attachment.stream.readAllBytes()).setContentType(attachment.mimetype);
Implemented in 94db4a5 and 72adeee

2025-03-04 08:30 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/process/data_transfer/service/InsertData.java
> +	private IdType createBinary(Binary binary)
Implemented in 94db4a5 and 72adeee

2025-03-04 08:32 UTC, wetret commented
> There are still Binary resource being serialized between BPMN tasks. Is this enough of an improvement to handle larger Binary resource?

I became aware of that as well, but already startet implementing for the `Multiple Attachments` support. Therefore the comments you wrote should be fixed in [PR #37](https://github.com/medizininformatik-initiative/mii-process-data-transfer/pull/37)

2025-03-22 07:59 UTC, wetret commented
closing without merging, as #37 contains all code of this PR as well

2025-03-22 07:59 UTC, closed without merging